from __future__ import annotations

from enum import StrEnum


class ProvisioningRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    READY_FOR_PLAN = "READY_FOR_PLAN"
    CANCELLED = "CANCELLED"
    TERRAFORM_INIT_RUNNING = "TERRAFORM_INIT_RUNNING"
    TERRAFORM_INIT_FAILED = "TERRAFORM_INIT_FAILED"
    TERRAFORM_INIT_SUCCEEDED = "TERRAFORM_INIT_SUCCEEDED"
    TERRAFORM_VALIDATE_RUNNING = "TERRAFORM_VALIDATE_RUNNING"
    TERRAFORM_VALIDATE_FAILED = "TERRAFORM_VALIDATE_FAILED"
    TERRAFORM_VALIDATE_SUCCEEDED = "TERRAFORM_VALIDATE_SUCCEEDED"
    PLAN_RUNNING = "PLAN_RUNNING"
    PLAN_FAILED = "PLAN_FAILED"
    PLAN_READY = "PLAN_READY"
    PLAN_DISABLED = "PLAN_DISABLED"
    SECURITY_SCAN_RUNNING = "SECURITY_SCAN_RUNNING"
    SECURITY_SCAN_FAILED = "SECURITY_SCAN_FAILED"
    SECURITY_SCAN_PASSED = "SECURITY_SCAN_PASSED"
    SECURITY_SCAN_BLOCKED = "SECURITY_SCAN_BLOCKED"
    COST_ESTIMATE_RUNNING = "COST_ESTIMATE_RUNNING"
    COST_ESTIMATE_FAILED = "COST_ESTIMATE_FAILED"
    COST_ESTIMATE_READY = "COST_ESTIMATE_READY"
    RISK_SUMMARY_READY = "RISK_SUMMARY_READY"
    GATES_EVALUATING = "GATES_EVALUATING"
    GATES_FAILED = "GATES_FAILED"
    GATES_PASSED = "GATES_PASSED"
    GATES_BLOCKED = "GATES_BLOCKED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"

    # Legacy Phase B statuses kept for existing local data compatibility.
    VALIDATION_PENDING = "VALIDATION_PENDING"
    PLAN_PENDING = "PLAN_PENDING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPLIED = "APPLIED"
    FAILED = "FAILED"


class ProvisioningArtifactType(StrEnum):
    REQUEST_INPUT = "REQUEST_INPUT"
    TFVARS = "TFVARS"
    PLAN = "PLAN"
    EVIDENCE = "EVIDENCE"
    TERRAFORM_INIT_LOG = "TERRAFORM_INIT_LOG"
    TERRAFORM_VALIDATE_LOG = "TERRAFORM_VALIDATE_LOG"
    TERRAFORM_PLAN_LOG = "TERRAFORM_PLAN_LOG"
    TERRAFORM_PLAN_BINARY = "TERRAFORM_PLAN_BINARY"
    TERRAFORM_PLAN_JSON = "TERRAFORM_PLAN_JSON"
    TERRAFORM_WORKSPACE_METADATA = "TERRAFORM_WORKSPACE_METADATA"
    CHECKOV_JSON = "CHECKOV_JSON"
    CHECKOV_LOG = "CHECKOV_LOG"
    INFRACOST_JSON = "INFRACOST_JSON"
    INFRACOST_LOG = "INFRACOST_LOG"
    RISK_SUMMARY_JSON = "RISK_SUMMARY_JSON"
    RISK_SUMMARY_MARKDOWN = "RISK_SUMMARY_MARKDOWN"
    GATES_RESULT_JSON = "GATES_RESULT_JSON"


class ProvisioningApprovalDecision(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ProvisioningApprovalLevel(StrEnum):
    STANDARD = "STANDARD"
    PRODUCTION = "PRODUCTION"
    BREAKGLASS = "BREAKGLASS"
