from __future__ import annotations

from enum import StrEnum


class ProvisioningRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    READY_FOR_PLAN = "READY_FOR_PLAN"
    CANCELLED = "CANCELLED"
    TERRAFORM_INIT_RUNNING = "TERRAFORM_INIT_RUNNING"
    TERRAFORM_INIT_FAILED = "TERRAFORM_INIT_FAILED"
    TERRAFORM_INIT_SUCCEEDED = "TERRAFORM_INIT_SUCCEEDED"
    TERRAFORM_VALIDATE_RUNNING = "TERRAFORM_VALIDATE_RUNNING"
    TERRAFORM_VALIDATE_FAILED = "TERRAFORM_VALIDATE_FAILED"
    TERRAFORM_VALIDATE_SUCCEEDED = "TERRAFORM_VALIDATE_SUCCEEDED"
    PLAN_RUNNING = "PLAN_RUNNING"
    PLAN_FAILED = "PLAN_FAILED"
    PLAN_READY = "PLAN_READY"
    PLAN_DISABLED = "PLAN_DISABLED"

    # Legacy Phase B statuses kept for existing local data compatibility.
    VALIDATION_PENDING = "VALIDATION_PENDING"
    PLAN_PENDING = "PLAN_PENDING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    APPLIED = "APPLIED"
    FAILED = "FAILED"


class ProvisioningArtifactType(StrEnum):
    REQUEST_INPUT = "REQUEST_INPUT"
    TFVARS = "TFVARS"
    PLAN = "PLAN"
    EVIDENCE = "EVIDENCE"
    TERRAFORM_INIT_LOG = "TERRAFORM_INIT_LOG"
    TERRAFORM_VALIDATE_LOG = "TERRAFORM_VALIDATE_LOG"
    TERRAFORM_PLAN_LOG = "TERRAFORM_PLAN_LOG"
    TERRAFORM_PLAN_BINARY = "TERRAFORM_PLAN_BINARY"
    TERRAFORM_PLAN_JSON = "TERRAFORM_PLAN_JSON"
    TERRAFORM_WORKSPACE_METADATA = "TERRAFORM_WORKSPACE_METADATA"
