from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel, Field, field_validator

from reports.enums import BrandTheme


class ReportBranding(BaseModel):
    company_name: str = Field(default="Northbound Control Tower", min_length=1, max_length=160)
    logo_url: str | None = Field(default=None, max_length=512)
    primary_color: str = "#0f172a"
    secondary_color: str = "#1e293b"
    footer_text: str = "Generated by Northbound Control Tower"
    generated_by_text: str = "Northbound Control Tower"
    theme: BrandTheme = BrandTheme.DEFAULT

    @field_validator("primary_color", "secondary_color")
    @classmethod
    def validate_hex_color(cls, value: str) -> str:
        if not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
            raise ValueError("Color must be a six-digit hex value")
        return value

    def as_template_data(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


def merge_branding(payload: dict[str, Any] | None) -> ReportBranding:
    return ReportBranding(**(payload or {}))
